mod.id = "templatemod"
mod.name = "Template Mod"
mod.group = "dev.redheris.example"
mod.version = "0.0.1"
mod.version_type = "ALPHA"
mod.fabric_loader = "0.18.4"
loomx.loom_version = "1.16-SNAPSHOT"

publish.modrinth = "# Modrinth mod slug"
publish.curseforge_id = "# Curseforge numeric mod ID"
publish.curseforge_slug = "# Curseforge mod slug"
publish.github_repo = "Redheris/RhMods-Template"
publish.mod_icon_url = "https://i.imgur.com/GmVIBYV.png"
publish.announce_for = "26.1" # "none" if no announcement
publish.dry_run = "false"

["1.21.8"]
# Minecraft dependency for fabric.mod.json e.g. ">=1.21.6 <=1.21.8"
mc_dep = "1.21.8"
# Release title for Modrinth and Curseforge
release_title = "1.21.8"
# Space-separated compatible versions for publishing e.g. "1.21.8 1.21.11 26.1"
mc_targets = "1.21.8"
# Dependencies
fabric_api = "0.136.1+1.21.8"
# Mappings
parchment = "1.21.8:2025.09.14"
mojbackward = "1.21.8+build.3"

["1.21.11"]
mc_dep = "1.21.11"
release_title = "1.21.11"
mc_targets = "1.21.11"
# Dependencies
fabric_api = "0.141.3+1.21.11"
# Mappings
parchment = "1.21.11:2025.12.20"

["26.1"]
mc_dep = "26.1"
mc_dep_fabric ="~26.1"
release_title = "26.1"
mc_targets = "26.1"
# Dependencies
fabric_api = "0.145.1+26.1"
